### ISSUE TITLE
Mettre le code applicatif dans le dossier app

### ISSUE THREAD

**Issue by alexpirine** [Qotto/gw-standardpro-contacts-exporter#2]
Tout le code applicatif doit être dans un dossier appelé `app`.

Voici un exemple de projet correctement structuré :

https://github.com/Qotto/app-installations-data-provider

**Comment by alexpirine** [comment]
Attention, les fichiers des dépendances de Pipenv doivent rester à la racine, pas dans app !

Tu peux regarder simplement ce qui se fait sur le projet dont je t'ai mentionné le lien plus haut :)

**Comment by andil-ADEBIYI** [comment]
modification effectuer
